<?php

use JetBrains\PhpStorm\Language;

/**
 * implements hook_menu()
 */
function cronmonitor_menu()
{
  $items = array();
  $items['admin/config/cronmonitor'] = array(
    'title' => 'Cron Monitor Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cronmonitor_admin_form'),
    'access arguments' => array('administer cronmonitor'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -1,
  );
  return $items;
}

/**
 * implements hook_permission()
 */

function cronmonitor_permission()
{
  return array(
    'administer cronmonitor' => array(
      'title' => 'Administer Cron Monitor',
      'description' => 'Administer Cron Monitor',
    ),
  );
}

/**
 * Adminsitration form for Cron Monitor.
 */

function cronmonitor_admin_form($form, &$form_state)
{
  $form['cronmonitor_enable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Cron Monitor'),
    '#default_value' => variable_get('cronmonitor_enable', 0),
  );

  $form['cronmonitor_email_text'] = array(
    '#type' => 'textarea',
    '#title' => t('text to send to email'),
    '#default_value' => variable_get('cronmonitor_email_text', ''),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_cron().
 */
function cronmonitor_cron()
{
  if (variable_get('cronmonitor_enable', 0)) {
    //send cron monitor email
    drupal_mail('cronmonitor', 'cronmonitor_email', 'musab.mohamed206@gmail.com', language_default());
  }
}

/**
 * Implements hook_mail().
 */
function cronmonitor_mail($key, &$message, $params)
{
  if (variable_get('cronmonitor_enable', 0)) {
    if ($key == 'cronmonitor_email') {
      $message['body'] = variable_get('cronmonitor_email_text', '');
    }
  }
}
