<?php

/**
 * Implementation of hook_block_info().
 */

function user_info_block_block_info()
{
  $blocks['user_info_block'] = array(
    'info' => t('User information block'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */

function user_info_block_block_view($delta = '')
{
  $block = array();
  switch ($delta) {
    case 'user_info_block':
      $block['subject'] = t('User information');
      $block['content'] = user_info_block();
      break;
  }

  return $block;
}

/**
 * Implementation of function block content.
 */

function user_info_block()
{
  global $user;
  $user_info = user_load($user->uid);
  $output = '';
  if ($user->uid != 0) {
    $output = $user->name . ' ' . $user->mail . ' ' . $user_info->field_job['und'][0]['value'];
  }

  return $output;
}
